[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python_benchmark_runner"
version = "0.0.1"

[project.scripts]
python_benchmark_runner = "src.main:main"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]